//
// ActionSurvey.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ActionSurvey: Codable {

    /** Questions shown to the user. */
    public var questions: [JourneySurveyQuestion]?

    public init(questions: [JourneySurveyQuestion]?) {
        self.questions = questions
    }


}

