//
// AdherenceExplanationAsyncResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class AdherenceExplanationAsyncResponse: Codable {

    /** A reference to the job that was started by the request */
    public var job: AdherenceExplanationJobReference?

    public init(job: AdherenceExplanationJobReference?) {
        self.job = job
    }


}

