//
// AvailableMediaTypeEntityListing.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class AvailableMediaTypeEntityListing: Codable {

    public var entities: [AvailableMediaType]?

    public init(entities: [AvailableMediaType]?) {
        self.entities = entities
    }


}

