//
// BulkCallbackDisconnectRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class BulkCallbackDisconnectRequest: Codable {

    /** The list of requests to disconnect callbacks in bulk */
    public var callbackDisconnectIdentifiers: [CallbackDisconnectIdentifier]?

    public init(callbackDisconnectIdentifiers: [CallbackDisconnectIdentifier]?) {
        self.callbackDisconnectIdentifiers = callbackDisconnectIdentifiers
    }


}

