//
// BulkResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class BulkResult: Codable {

    /** Error details if the operation failed. */
    public var error: BulkError?
    /** The result of the operation if it succeeded. */
    public var entity: JSON?

    public init(error: BulkError?, entity: JSON?) {
        self.error = error
        self.entity = entity
    }


}

