//
// BulkOrganizationsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class BulkOrganizationsRequest: Codable {

    public var entities: [ExternalOrganization]?

    public init(entities: [ExternalOrganization]?) {
        self.entities = entities
    }


}

