//
// BulkUpdateShiftTradeStateResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class BulkUpdateShiftTradeStateResult: Codable {

    public var entities: [BulkUpdateShiftTradeStateResultItem]?

    public init(entities: [BulkUpdateShiftTradeStateResultItem]?) {
        self.entities = entities
    }


}

