//
// ConfusionInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ConfusionInfo: Codable {

    /** Confusion details between this utterance and other intents. */
    public var intents: [ConfusionIntentInfo]?

    public init(intents: [ConfusionIntentInfo]?) {
        self.intents = intents
    }


}

