//
// ConfusionDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ConfusionDetails: Codable {

    /** Confusion details between this utterance and other intents. */
    public var intents: [ConfusionIntentDetails]?

    public init(intents: [ConfusionIntentDetails]?) {
        self.intents = intents
    }


}

