//
// ConsultTransferResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ConsultTransferResponse: Codable {

    /** Participant ID to whom the call is being transferred. */
    public var destinationParticipantId: String?

    public init(destinationParticipantId: String?) {
        self.destinationParticipantId = destinationParticipantId
    }


}

