//
// ContextEntity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ContextEntity: Codable {

    /** The name of the entity. */
    public var name: String?

    public init(name: String?) {
        self.name = name
    }


}

