//
// ContactListTemplateBulkRetrieveBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ContactListTemplateBulkRetrieveBody: Codable {

    /** The IDs of the Contact List Templates to retrieve. */
    public var ids: [String]?

    public init(ids: [String]?) {
        self.ids = ids
    }


}

