//
// ConversationTagsUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ConversationTagsUpdate: Codable {

    /** The external tag associated with the conversation. */
    public var externalTag: String?

    public init(externalTag: String?) {
        self.externalTag = externalTag
    }


}

