//
// DnclistDownloadReadyExportUri.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class DnclistDownloadReadyExportUri: Codable {

    public var uri: String?
    public var exportTimestamp: String?
    public var additionalProperties: [String:JSON]?

    public init(uri: String?, exportTimestamp: String?, additionalProperties: [String:JSON]?) {
        self.uri = uri
        self.exportTimestamp = exportTimestamp
        self.additionalProperties = additionalProperties
    }


}

