//
// EdgeVersionInformation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class EdgeVersionInformation: Codable {

    public var softwareVersion: String?

    public init(softwareVersion: String?) {
        self.softwareVersion = softwareVersion
    }


}

