//
// EdgeMetricsTopicEdgeMetricSubsystemMedia.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class EdgeMetricsTopicEdgeMetricSubsystemMedia: Codable {

    public var processName: String?
    public var delayMs: Int?

    public init(processName: String?, delayMs: Int?) {
        self.processName = processName
        self.delayMs = delayMs
    }


}

