//
// EmailSetup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class EmailSetup: Codable {

    /** The root PureCloud domain that all sub-domains are created from. */
    public var rootDomain: String?

    public init(rootDomain: String?) {
        self.rootDomain = rootDomain
    }


}

