//
// EndTransferEvent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class EndTransferEvent: Codable {

    public enum FinalState: String, Codable { 
        case completed = "Completed"
        case canceled = "Canceled"
        case failed = "Failed"
    }
    /** A unique (V4 UUID) eventId for this event */
    public var eventId: String?
    /** A Date Time representing the time this event occurred. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss[.mmm]Z */
    public var eventDateTime: Date?
    /** A unique Id (V4 UUID) identifying this conversation */
    public var conversationId: String?
    /** The id (V4 UUID) used to identify the transfer already started by the external platform. */
    public var commandId: String?
    /** Indicates whether the transfer completed successfully, was cancelled, or failed for some reason. */
    public var finalState: FinalState?
    /** The id (V4 UUID) of the communication that was being transferred. */
    public var objectCommunicationId: String?

    public init(eventId: String?, eventDateTime: Date?, conversationId: String?, commandId: String?, finalState: FinalState?, objectCommunicationId: String?) {
        self.eventId = eventId
        self.eventDateTime = eventDateTime
        self.conversationId = conversationId
        self.commandId = commandId
        self.finalState = finalState
        self.objectCommunicationId = objectCommunicationId
    }


}

