//
// EvaluationQualityV2TopicEvaluationSource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class EvaluationQualityV2TopicEvaluationSource: Codable {

    public var evaluationSourceType: String?
    public var evaluationSourceId: String?
    public var evaluationSourceName: String?

    public init(evaluationSourceType: String?, evaluationSourceId: String?, evaluationSourceName: String?) {
        self.evaluationSourceType = evaluationSourceType
        self.evaluationSourceId = evaluationSourceId
        self.evaluationSourceName = evaluationSourceName
    }


}

