//
// ExternalContactsContactChangedTopicLineId.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ExternalContactsContactChangedTopicLineId: Codable {

    public var ids: [ExternalContactsContactChangedTopicLineUserId]?
    public var displayName: String?

    public init(ids: [ExternalContactsContactChangedTopicLineUserId]?, displayName: String?) {
        self.ids = ids
        self.displayName = displayName
    }


}

