//
// FlowExecutionAggregateQueryResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class FlowExecutionAggregateQueryResponse: Codable {

    public var results: [FlowExecutionAggregateDataContainer]?

    public init(results: [FlowExecutionAggregateDataContainer]?) {
        self.results = results
    }


}

