//
// JourneyWebEventsNotificationSegmentAssignmentMessage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class JourneyWebEventsNotificationSegmentAssignmentMessage: Codable {

    public var segment: JourneyWebEventsNotificationSegment?

    public init(segment: JourneyWebEventsNotificationSegment?) {
        self.segment = segment
    }


}

