//
// LimitsEntityListing.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class LimitsEntityListing: Codable {

    public var entities: [Limit]?

    public init(entities: [Limit]?) {
        self.entities = entities
    }


}

