//
// LocationImage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class LocationImage: Codable {

    /** Height and/or width of image. ex: 640x480 or x128 */
    public var resolution: String?
    public var imageUri: String?

    public init(resolution: String?, imageUri: String?) {
        self.resolution = resolution
        self.imageUri = imageUri
    }


}

