//
// MatchCriteriaTestResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Results of a matching expression */

public class MatchCriteriaTestResult: Codable {

    public enum Operator: String, Codable { 
        case greaterThanOrEqual = "GreaterThanOrEqual"
        case lessThanOrEqual = "LessThanOrEqual"
        case equal = "Equal"
        case notEqual = "NotEqual"
        case lessThan = "LessThan"
        case greaterThan = "GreaterThan"
        case notIn = "NotIn"
        case _in = "In"
        case contains = "Contains"
        case all = "All"
        case exists = "Exists"
        case size = "Size"
    }
    /** The Goessner json path of the field to match */
    public var jsonPath: String?
    /** The type of operation to perform for matching check */
    public var _operator: Operator?
    /** The value to match on. Only one of value and values can be included */
    public var value: JSON?
    /** The list of values to match on. Only one of value and values can be included */
    public var values: [JSON]?
    /** The generated json path condition */
    public var generatedJsonPathCondition: String?
    /** Did the generated json path condition match */
    public var match: Bool?
    /** The json paths and their values that were compared */
    public var jsonPathExtraction: [MatchTestResult]?

    public init(jsonPath: String?, _operator: Operator?, value: JSON?, values: [JSON]?, generatedJsonPathCondition: String?, match: Bool?, jsonPathExtraction: [MatchTestResult]?) {
        self.jsonPath = jsonPath
        self._operator = _operator
        self.value = value
        self.values = values
        self.generatedJsonPathCondition = generatedJsonPathCondition
        self.match = match
        self.jsonPathExtraction = jsonPathExtraction
    }

    public enum CodingKeys: String, CodingKey { 
        case jsonPath
        case _operator = "operator"
        case value
        case values
        case generatedJsonPathCondition
        case match
        case jsonPathExtraction
    }


}

