//
// NluDomainVersionTrainingResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class NluDomainVersionTrainingResponse: Codable {

    /** A message indicating result of the action. */
    public var message: String?
    public var version: NluDomainVersion?

    public init(message: String?, version: NluDomainVersion?) {
        self.message = message
        self.version = version
    }


}

