//
// OpenInboundMessageContent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Message content element. */

public class OpenInboundMessageContent: Codable {

    /** Attachment content. */
    public var attachment: OpenContentAttachment?

    public init(attachment: OpenContentAttachment?) {
        self.attachment = attachment
    }


}

