//
// PatchContextPattern.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class PatchContextPattern: Codable {

    /** A list of one or more criteria to satisfy. */
    public var criteria: [PatchEntityTypeCriteria]?

    public init(criteria: [PatchEntityTypeCriteria]?) {
        self.criteria = criteria
    }


}

