//
// QueueConversationSocialExpressionEventTopicWorkflow.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Information about the workflow. */

public class QueueConversationSocialExpressionEventTopicWorkflow: Codable {

    /** The id of the workflow */
    public var workflowId: String?

    public init(workflowId: String?) {
        self.workflowId = workflowId
    }


}

