//
// RateLimitAggregateQueryResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class RateLimitAggregateQueryResponse: Codable {

    public var results: [RateLimitAggregateDataContainer]?

    public init(results: [RateLimitAggregateDataContainer]?) {
        self.results = results
    }


}

