//
// RetentionDuration.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class RetentionDuration: Codable {

    public var archiveRetention: ArchiveRetention?
    public var deleteRetention: DeleteRetention?

    public init(archiveRetention: ArchiveRetention?, deleteRetention: DeleteRetention?) {
        self.archiveRetention = archiveRetention
        self.deleteRetention = deleteRetention
    }


}

