//
// ShiftStartVariance.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ShiftStartVariance: Codable {

    /** Days for which shift start variance is configured */
    public var applicableDays: [String]?
    /** Maximum variance in minutes across shift starts */
    public var maxShiftStartVarianceMinutes: Int?

    public init(applicableDays: [ApplicableDays]?, maxShiftStartVarianceMinutes: Int?) {
        self.applicableDays = applicableDays
        self.maxShiftStartVarianceMinutes = maxShiftStartVarianceMinutes
    }


}

