//
// StatEventUserTopicIntervalMetrics.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class StatEventUserTopicIntervalMetrics: Codable {

    public var interval: String?
    public var metrics: [StatEventUserTopicMetricStats]?

    public init(interval: String?, metrics: [StatEventUserTopicMetricStats]?) {
        self.interval = interval
        self.metrics = metrics
    }


}

