//
// SupportCenterImageSource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class SupportCenterImageSource: Codable {

    /** Default URL for image */
    public var defaultUrl: String?

    public init(defaultUrl: String?) {
        self.defaultUrl = defaultUrl
    }


}

