//
// SupportedDialectsEntityListing.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class SupportedDialectsEntityListing: Codable {

    public var entities: [TranscriptionEngines]?

    public init(entities: [TranscriptionEngines]?) {
        self.entities = entities
    }


}

