//
// TeamMembers.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class TeamMembers: Codable {

    /** A list of the ids of the members to add or remove */
    public var memberIds: [String]?

    public init(memberIds: [String]?) {
        self.memberIds = memberIds
    }


}

