//
// UpdateAnalyticsDataRetentionRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class UpdateAnalyticsDataRetentionRequest: Codable {

    /** Analytics data retention period in days to set for the organization. */
    public var retentionDays: Int?

    public init(retentionDays: Int?) {
        self.retentionDays = retentionDays
    }


}

