//
// UserStationChangeTopicUserStations.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class UserStationChangeTopicUserStations: Codable {

    public var associatedStation: UserStationChangeTopicUserStation?

    public init(associatedStation: UserStationChangeTopicUserStation?) {
        self.associatedStation = associatedStation
    }


}

