//
// ValueWrapperHrisTimeOffType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ValueWrapperHrisTimeOffType: Codable {

    /** The value for the associated field */
    public var value: HrisTimeOffType?

    public init(value: HrisTimeOffType?) {
        self.value = value
    }


}

